---
title: "Reseña: Está entre nosotros"
subtitle: "¿De dónde sale y hasta dónde puede llegar la extrema derecha que no vimos venir?"
author: "Tomás Bustos"
date: 2025-12-01
categories: ["publicaciones", "empleo", "electoral"]
lang: es
format:
  html:
    toc: true
    toc-depth: 3
    toc-title: contenido 
    page-layout: article
---

::: justificado
*Publicado en [Papeles de Trabajo](https://revistasacademicas.unsam.edu.ar/index.php/papdetrab/issue/view/129), Vol. 19 Núm. 36 (2025) editada por la Universidad Nacional de San Martín. Publicación disponible [aquí](https://revistasacademicas.unsam.edu.ar/index.php/papdetrab/article/view/2329/4388).*

# Combatientes: sensibilidades juveniles en la reconfiguración política argentina

Reseña: Semán, Pablo (2024). *Está entre nosotros. ¿De dónde sale y hasta dónde puede llegar la extrema derecha que no vimos venir?* Ciudad Autónoma de Buenos Aires: Siglo XXI Editores Argentina, 208 p., ISBN 978-897-801-295-7.

La irrupción de La Libertad Avanza en el escenario político nacional, además de una sorpresa, representó una ruptura en el esquema político-partidario presente hasta entonces. Si el peronismo y la alianza constituida alrededor de Propuesta Republicana (PRO) sugerían un caso típico de bicoalicionismo, el asalto por derecha de los libertarios transformó por completo la dinámica electoral del país. El escenario de tercios de las elecciones presidenciales de 2023 reveló la decepción de los votantes argentinos con las últimas coaliciones de gobierno. En *Está entre nosotros: ¿De dónde sale y hasta dónde puede llegar la extrema derecha que no vimos venir?* se aborda el origen y crecimiento de los grupos libertarios en Argentina, sectores sociales cuyas demandas supieron ser escuchadas por las vocerías públicas de La Libertad Avanza. El libro, compilado y coordinado por Pablo Semán, se compone por cuatro capítulos de distintos autores que logran aproximarse al fenómeno desde perspectivas complementarias, oportunamente conectadas, describiendo de manera diversa y detallada el proceso que tiene un punto cúlmine en la presidencia de Javier Milei.

Ya en su introducción, se sugieren seis grandes determinaciones para comprender el descontento popular contemporáneo en la Argentina (p16). En primer lugar, el texto señala el estancamiento y progresivo deterioro de las condiciones socioeconómicas desde 1975, reflejado en el decrecimiento del PBI per cápita y en los aumentos de los picos de pobreza, con breves períodos de mejora que no logran revertir la tendencia ascendente posterior. En segundo lugar, destaca el surgimiento y expansión de nuevas formas de interacción digital, sujetos inicialmente autónomos pero hoy incorporados a un complejo ecosistema mediático compuesto por redes sociales, medios y otros circuitos de mediación política. Tercero, observa la pérdida del poder simbólico del Estado. El constante cuestionamiento de sus acciones, otrora agente indiscutible de desarrollo económico y social, revela una crisis profunda de legitimidad. A esto se suma un cuarto elemento: el creciente cuestionamiento al peronismo por su impotente conducción durante las últimas dos décadas, provocando distancias, desconocimientos, reproches y ajenidades para el propio movimiento. La quinta determinación es la extensión de un impulso individualista, entendido como una aspiración vital a la realización personal, el desarrollo interior y la superación individual, incluso dentro de condiciones materiales adversas. Finalmente, se incorpora la pandemia como evento disruptivo que exacerbó las tensiones, acelerando procesos de fragmentación, repliegue subjetivo y desconfianza para con el Estado. En este marco, se sostiene que la prédica furiosa contra el Estado, los partidos políticos y la economía se hizo eco de un lazo ya erosionado y frágil de estos elementos con la sociedad argentina.

Conviene recorrer, aún de manera sintética, los distintos capítulos que incluye el texto. En el primero, Sergio Morresi y Martín Vicente rastrean cómo La Libertad Avanza presenta líneas de continuidad con los partidos políticos históricos de derecha que disputaron las distintas esferas del Estado a través del tiempo. En concreto, acuñan el concepto de *fusionismo* para describir el encuentro sin síntesis entre una línea más liberal y una línea más conservadora-autoritaria; un encuentro que sucedió en otros momentos históricos. En el segundo capítulo, Melina Vázquez describe las motivaciones de los militantes libertarios; su reivindicación de ser de *derecha* que los emparenta con las militancias liberales como las de la UPAU-UCeDé y su búsqueda de representación popular que los diferencia con la militancia más reciente de los jóvenes PRO. En el tercer capítulo, Ezequiel Saferstein analiza la cultura masiva y la producción de libros para describir los modos de legitimación de distintos referentes libertarios (como Agustín Laje o Nicolás Márquez) que fueron tempranos cuestionadores de la lectura kirchnerista de la última dictadura militar primero y de los planteos feministas en años más recientes. En el último capítulo, Pablo Semán y Nicolás Welschinger presentan la idea de juventudes mejoristas que se describirá a continuación con mayor atención.

El capítulo *juventudes mejoristas y el mileísmo de masas. Por qué el libertarismo las convoca y ellas responden* es de particular importancia por elaborar la relación entre las trayectorias vitales y la propensión al voto libertario dentro de un sector de la juventud argentina*.* Pablo Semán es investigador del CONICET radicado en la UNSAM, formado en sociología y antropología, dedicado a estudiar experiencias religiosas, musicales, literarias y políticas de los sectores populares. Por su parte, Nicolás Welschinger está formado en sociología y tiene trabajos realizados en torno a la crítica de las juventudes al Estado y la situación social durante la pandemia. El libro se publica en el mes de julio de 2024, ocho meses después del sorprendente triunfo electoral de La Libertad Avanza y es parte de una serie (aún acotada) de producción bibliográfica que intenta comprender al sector de la juventud que traccionó el apoyo al candidato ganador.

El capítulo indaga en las experiencias de jóvenes de sectores medios y populares, habitantes del Área Metropolitana de Buenos Aires (AMBA), de edades entre 17 y 26 años, a través de una estrategia cualitativa. La investigación estuvo compuesta por entrevistas biográficas y grupos focales -con métodos bien diferenciados de la consultoría electoral, por utilizar ambientes más descontracturados, personas reclutadas a través de los primeros participantes y sin cuotas definidas a priori-. El objetivo de la investigación fue explorar una conexión posible entre el modo de vida de trabajadores jóvenes y sus posiciones políticas electorales. La construcción de una derecha popular no es vista como personas simplemente engañadas o convencidas por la retórica elocuente de un referente, sino como la configuración de una sensibilidad a partir de experiencias económicas específicas, sensibilidades que dan lugar a prácticas e ideales fértiles para ciertas doctrinas e influencias. Concretamente, ¿qué es lo que encuentran lo sinvestigadores en esta investigación?

Semán y Welschinger refieren casos ejemplificadores de lo que ellos llaman *juventudes mejoristas*, personas cuyo ingreso se resuelve en emprendimientos o trabajos relativamente independientes -fuera de la relación clásica de asalariados- a costa de un gran esfuerzo personal. Hay dos personas que son de especial interés para presentar las nociones centrales de los autores. Juan desarrolla una gran autodisciplina en vistas de formarse en programación por fuera de la educación formal, considera a las carreras universitarias como una inversión excesiva en relación con las oportunidades laborales que habilitan las *academias online*. ¿Qué implica este desarrollo para un joven de 21 años? Se compromete a dormir lo mínimo e indispensable para aumentar sus tiempos de estudio, adopta una alimentación particular, utiliza técnicas para maximizar los períodos de concentración, lee material del género autoayuda para sostener la motivación con su propio proyecto. El segundo caso de interés es cuidadora en un asilo de personas mayores. Belén complementa su trabajo con una aplicación de reparto donde administra sus propios horarios, aprovecha la flexibilidad para reforzar el ingreso cuando su situación personal lo demanda y decide no contar con obra social ni seguro de moto para ahorrar dinero. Con un hijo en edad escolar, la capacidad de definir los horarios de la jornada le permite prescindir de servicios como transporte privado o niñera que le costarían un dinero que no tiene. Ambas situaciones son ejemplificadoras de un sentir generalizado en este sector de la juventud: la autonomía y el mérito se vuelven guías rectoras entre quienes forjan sus personalidades a la vera del empleo asalariado y las regulaciones laborales. Las *juventudes mejoristas* se disponen a “encontrarle la vuelta” disciplinando cuerpo y mente para sintonizar con un mercado laboral cada vez más cerrado y expulsivo, en un gesto semejante al de los “combatientes que están dispuestos a hacer todos los sacrificios y pruebas que la economía exige” (p173), un temperamento que involucra el rendimiento laboral, físico, estético y emocional. Lo interesante de la idea de combatiente como respuesta a la crisis es su carácter moral: la superación personal orientada a amortiguar las consecuencias de una empleabilidad que se vuelve cada vez más costosa. No depende únicamente de su efectividad económica, cobra sentido como formadora de un modo de ser y estar en el mundo de hoy. Los investigadores resaltan tres críticas de importancia que anudan con las sensibilidades configuradas por esta forma de enfrentarse al mercado de trabajo, especialmente en la pospandemia: el cuestionamiento a la política, al Estado y a la economía. La crítica a los políticos, como una comunidad aislada de la realidad, injustamente privilegiada y sin poder ni voluntad de acción ante el descarte del mercado. La crítica al estado del Estado, por sus visibles e inadmisibles deficiencias en las áreas de educación, salud y seguridad, consideradas como sus funciones mínimas. Por último, la crítica a la economía: el palpable empeoramiento de las condiciones vitales entre 2013 y 2023 consolida un malestar específicamente generacional cristalizado en la falta de un puesto de trabajo estable, la inaccesibilidad a una vivienda propia o la inestabilidad cotidiana de los precios de los productos más elementales.

El principal aporte del texto es evitar explicaciones basadas en el engaño de masas, la infalibilidad de ciertas estrategias de comunicación o la irrupción ahistórica de un movimiento impensado. La potencia de sostener que “las convocatorias liberales son exitosas porque sintonizan con las formas en que los sujetos se narran a sí mismos” (p.183) reside en anudar los distintos determinantes en una descripción coherente: la forma de ganarse la vida, los cambios introducidos por las redes sociales, el malestar generacional de mediano plazo y el detonante de la pandemia encuentran armonía en el capítulo de Semán y Welschinger. Sin despreciar la capacidad de interpelación de la *performance* del líder de La Libertad Avanza, se le atribuye menor centralidad al carácter mesiánico en la figura de Milei y a las pretensiones grandilocuentes de su equipo de comunicación: el Presidente es un político cuyo acierto fue sostener la visión y agenda de las juventudes mejoristas mejor que otros.

Vale la pena preguntarse por el lugar de los sectores descriptos por los autores dentro del universo de votantes libertarios. Teniendo en cuenta la territorialidad de los ocho millones de votos obtenidos por La Libertad Avanza en las elecciones generales de 2023, resulta difícil acotar el análisis a la experiencia típica de los jóvenes en el AMBA: los mejores resultados fueron obtenidos en provincias como Misiones, Mendoza o Salta con valores cercanos al 40%, marcando un fuerte contraste con el 24% obtenido en el Gran Buenos Aires o el 19% obtenido en la Ciudad de Buenos Aires. ¿Son los jóvenes de sectores populares quienes traccionaron el apoyo a Milei en todas las provincias? ¿Es igual la sensibilidad construida por los jóvenes de sectores populares en ciudades como Godoy Cruz, Posadas o Hurlingham? Si las juventudes mejoristas son las más ruidosas dentro del mileísmo, ¿en qué sesgos pueden caer las conclusiones extraídas de investigaciones que se basan exclusivamente en ese sector para caracterizar su apoyo? El libro coordinado por Semán tiene la virtud de abrir la discusión y caracterizar un sector de la juventud. Al mismo tiempo, confrontando con los resultados agregados, cabe preguntarse: ¿qué otras experiencias en el seno del voto libertario no están siendo observadas ni narradas?

Para concluir, *Está entre nosotros* logra dilucidar, con la observación atenta de los jóvenes habitantes del AMBA, una relación novedosa entre sus experiencias vitales actuales y la transformación de la política nacional. Es una invitación a seguir pensando sobre las nuevas sensibilidades que intervienen hoy en la democracia argentina.
:::
